//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationVol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Reservations = new HashSet<Reservation>();
        }

        public Client(decimal idClient, string nomClient, string prenomClient, string telephoneClient, string emailClient, bool? clientPrincipal, decimal? ageClient)
        {
            this.idClient = idClient;
            this.nomClient = nomClient;
            this.prenomClient = prenomClient;
            this.telephoneClient = telephoneClient;
            this.emailClient = emailClient;
            this.clientPrincipal = clientPrincipal;
            this.ageClient = ageClient;
        }

        public decimal idClient { get; set; }
        public string nomClient { get; set; }
        public string prenomClient { get; set; }
        public string telephoneClient { get; set; }
        public string emailClient { get; set; }
        public Nullable<bool> clientPrincipal { get; set; }
        public Nullable<decimal> ageClient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
