//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationVol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalite
    {
        public decimal idPenalite { get; set; }
        public Nullable<decimal> montant { get; set; }
        public string idReservation { get; set; }
        public Nullable<decimal> idTransaction { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
