//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationVol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Penalites = new HashSet<Penalite>();
            this.Transactions = new HashSet<Transaction>();
        }

        public Reservation(string idReservation, string dateReservation, decimal? idVol, decimal? idClient)
        {
            this.idReservation = idReservation;
            this.dateReservation = dateReservation;
            this.idVol = idVol;
            this.idClient = idClient;
        }

        public string idReservation { get; set; }
        public string dateReservation { get; set; }
        public Nullable<decimal> idVol { get; set; }
        public Nullable<decimal> idClient { get; set; }
        public Nullable<decimal> idConseiller { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Conseiller Conseiller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penalite> Penalites { get; set; }
        public virtual Vol Vol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
