//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationVol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.Penalites = new HashSet<Penalite>();
        }

        public Transaction(decimal idTransaction, string dateTransaction, decimal? montantTransaction, string idReservation)
        {
            this.idTransaction = idTransaction;
            this.dateTransaction = dateTransaction;
            this.montantTransaction = montantTransaction;
            this.idReservation = idReservation;
        }

        public decimal idTransaction { get; set; }
        public string dateTransaction { get; set; }
        public Nullable<decimal> montantTransaction { get; set; }
        public string idReservation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penalite> Penalites { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
